# ================================================================
# Fluent-Bit 서비스의 전역 행동 설정
# 수집 -> 전처리/추출 x -> 적재(배달) 컨셉
# logstash 연계가 없었다면 여기서 전처리/필터링 등 작업이 수행 될 수 있음
# ================================================================
[SERVICE]
    Flush       1       # 수집된 데이터를 몇 초 간격으로 내보낼 것인가(출력) | 현재 세팅값 : 1초마다 전송
    Log_Level   info    # Fluent-Bit 로그에 대한 레벨 설정 (error,warn,info,debug) | 현재 세팅값 : info부터 출력(info, debug)

# ================================================================
# 데이터 수집 Input -> 어디서 데이터를 가져올 것인가
# Input : sensor_json.log
# ================================================================
[Input]
    # 파일의 끝에서 읽어온다 -> 플러그인
    Name    tail
    # 읽어 올 로그 파일 경로 -> 날짜가 바뀌거나 파일이 커지면 어떻게 할지 해결해야함(리뷰)                  
    Path    /opt/airflow/sensor_logs/sensor_json.log
    # 해당 데이터에 tag 표시, 차후 output에서 Tag를 보고 어디로 전송할 지 결정
    Tag     sensor.json
    # 파일 내용을 미리 정의된 Parser에 기록된 파서를 활용해 구조화된 데이터로 인식                             
    Parser  json
# ================================================================
# Input : sensor_text.log
# ================================================================
[Input]
    # 파일의 끝에서 읽어온다 -> 플러그인
    Name    tail
    # 읽어 올 로그 파일 경로 -> 날짜가 바뀌거나 파일이 커지면 어떻게 할지 해결해야함(리뷰)                               
    Path    /opt/airflow/sensor_logs/sensor_text.log
    # 해당 데이터에 tag 표시, 차후 output에서 Tag를 보고 어디로 전송할 지 결정
    Tag     sensor.text
# ================================================================
# 데이터 배포 Output -> 데이터를 어디로 보낼 것인가
# Output : kafka
# ================================================================
[Output]
    # kafka 출력 플러그인 사용
    Name    kafka
    # 태그가 sensor.json 인 것만 필터링 
    Match   sensor.json
    # 전송할 엔드포인트(도커컴포즈에 있는 서비스명(컨테이너이름x)), 포트 => MSK의 엔드포인트가 된다
    Brokers kafka:9092
    # 카프카로 데이터를 보낼 때, 토픽명이 필요하다(ex. data_consumer) 
    Topics  factory-json-topic
    # 전송되는 데이터형식 지정 | json으로 유지
    Format  json                             
# ================================================================
# Output : logstash (http 전송)
# ================================================================
[Output]
    # Fluent-Bit -> logstash 간 프로토콜로 http 사용한다(보안고려시 https)
    Name    http
    # 태그가 sensor.text 인 것만 필터링 
    Match   sensor.text
    # 수신측의 서비스명 기재 -> 도커 컴포즈 상에서 logstash 서비스명
    Host    logstash
    # logstash로 보낼 때 url, port, 형식 
    Port    5044
    URI     /
    Format  json           