input {
    http {
        port => 5044
    }
}

filter {
    # 메세지에서 "ID=" 라는 표현이 포함될 경우만 파싱 진행(보험)
    # grok : 비정형 텍스트 
    # "[2026-04-24-13:31:30]  ID=AI-FACTORY-001 | TEMP=78.81 | HUM=13.43 |  STAT=RUNNING"
    # %[패턴명:필드명:데이터타입]
    if [message] =~ "ID=" {
        grok {
            match => {"message" => "\[%{TIMESTAMP_ISO8601:logtime}\]  ID=%{DATA:device_id} \| TEMP=%{NUMBER:temp:float} \| HUM=%{NUMBER:temp:float} \|  STAT=&{WORD:status}"}
        }
    }
}

output {
    kafka{
        bootstrap-servers => "kafka:9092"
        topic_id => "factory-text-topic"
        codec => json
    }
    # 확인용 콘솔 출력 로그에
    stdout {
        codec => rubydebug
    }
}